@startuml ArchitectureDiagram
skinparam actorStyle awesome
skinparam packageStyle rectangle

left to right direction
"Seller"  as Seller #79dbf0
"Certifier" as Certifier #9fd22a
"Buyer" as Buyer #45818e
"Account.sol" as Account #d5554c

Buyer --> EventTokenMarket.sol
rectangle Platform.sol #a561cc {
  Seller --> (listEvent)
  (listEvent) --> (commenceBidding)
  (commenceBidding) --> (placeBid/updateBid)
  (placeBid/updateBid) --> (closeBidding)
  (closeBidding) --> (buyTickets/refundTicket)
  (buyTickets/refundTicket) --> (sellerEndEvent)
  (sellerEndEvent) --> (platformEndEvent)
  Buyer <--> (buyTickets/refundTicket)
  Buyer -right-> (placeBid/updateBid)
}

rectangle Event.sol #ff7373 {
  (listEvent) --> (createEvent)
  (createEvent) --> (generateEventTickets)
}

rectangle Ticket.sol #faebd7 {
  (generateEventTickets) --> (addTicket)
}

rectangle Account.sol #c0d6e4 {
   Certifier --> (verifyAccount)
  (listEvent) <--> (isVerified)
  Account --> (certifyAccount)
}

EventTokenMarket.sol <-down-> EventTokenMarketAlgorithm.sol
EventToken.sol --> ERC20.sol
EventToken.sol --> EventTokenMarket.sol

rectangle EventToken.sol #93dc7f {
    (platformEndEvent) --> (mintToken)
    (mintToken) --> (Buyer)
    (approveToken)
    (burnToken)
}

rectangle EventTokenMarket.sol #b4eeb4 {
    (list)
    (unlist)
    (purchaseToken)
}

rectangle EventTokenMarketAlgorithm.sol #a0db8e {
    (buyTokens)
    (removeSellOrders)
}

rectangle ERC20.sol {
    (mint)
    (burn)
    (transferFrom)
    (approve)
}

@enduml