@startuml ArchitectureDiagram
!include <office/Users/user>
!include style.puml

' hide the circles in the diagram
hide circle
hide empty members

package " "<<Rectangle>>{
    class Platform COLOR_PLATFORM
    class Account COLOR_ACCOUNT
    class Ticket COLOR_TICKET
    class Event COLOR_EVENT
    class EventToken COLOR_EVENTTOKEN
    class ERC20 COLOR_ERC20
}

class "<$user>" as User COLOR_SPARE3

User .[COLOR_SPARE3]down.> Platform
Platform -[COLOR_PLATFORM]down> Account
Account --[COLOR_ACCOUNT]up> Platform
Platform .[COLOR_PLATFORM].> User


@enduml