!define COLOR_PLATFORM #1E90FF
!define COLOR_ACCOUNT #FF8C00
!define COLOR_EVENTTOKEN #00FFFF
!define COLOR_EVENT #DC143C
!define COLOR_ERC20 #BA55D3
!define COLOR_TICKET #FF69B4
!define COLOR_SPARE1 #FFFF00
!define COLOR_SPARE3 #00AA00

!define COLOR_PLATFORM_BOX #ADD8E6
!define COLOR_ACCOUNT_BOX #FAEBD7
!define COLOR_EVENTTOKEN_BOX #E0FFFF
!define COLOR_EVENT_BOX #F08080
!define COLOR_ERC20_BOX #DDA0DD
!define COLOR_TICKET_BOX #FFC0CB
!define COLOR_SPARE1_BOX #FFFACD
!define COLOR_SPARE3_BOX #98FB98